//parkir in (queue) 
//parkir out (queue)
//get all parkir in & out (jwt, cache) 
//get all parkir in & out (jwt, cache) 
//get parkir in  (jwt, cache) 
//get parkir out (jwt, cache) 
//get total income (jwt, cache, enc) 
//get total income today (jwt, cenc) 
//get total income thiis mouth (jwt, cache, enc) 